require: rubocop-rails

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'

Style/Documentation:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/WordArray:
  Enabled: false
Metrics/LineLength:
  Max: 120
Style/SymbolArray:
  Enabled: false
Layout/IndentFirstArrayElement:
  EnforcedStyle: consistent
Naming/VariableNumber:
  EnforcedStyle: snake_case
